### ISSUE TITLE
Telemetry

### ISSUE THREAD

**Issue by Miguel-hrvs** [PabloMK7/citra#43]
### Issue

I think that the emulator telemetry should be removed as it's a privacy problem since the original developers had to stop development. The things that are being really difficult to remove telemetry are the opengl and vulkan renderers. I got some help from one of the suyu commits: https://git.suyu.dev/suyu/suyu/commit/22f8b858a285468030f8f163c5ec31b80efb0ad3

These are the places with telemetry:
src/common/telemetry.cpp and h and from cmakelists.txt
src/core/core.cpp
src/core/core.h
src/core/telemetry_session.cpp and h and from cmakelists.txt
src/core/hle/service/apt/apt.cpp 
src/core/loader/ncch.cpp
src/video_core/renderer_opengl/gl_driver.cpp
src/video_core/renderer_vulkan/renderer_vulkan.cpp
src/video_core/renderer_vulkan/vk_instance.h
src/video_core/renderer_opengl/renderer_opengl.cpp
src/video_core/renderer_opengl/gl_texture_runtime.cpp
src/video_core/renderer_opengl/pica_to_gl.h
src/video_core/renderer_vulkan/vk_instance.cpp
src/video_core/renderer_opengl/gl_driver.h
src/citra/citra.cpp
src/webservice/telemetry_json.cpp and h and cmakelists.txt
src/citra_qt/main.cpp
src/citra_qt/compatdb.h and cpp
src/citra_qt/configuration/configure_web.cpp .h and .ui

**Comment by Daisouji** [comment]
What you do is open a pull request on github.

**Comment by Miguel-hrvs** [comment]
To make the pull request, first I need to finish the telemetry removal and I need help for that.

**Comment by Miguel-hrvs** [comment]
Draft uploaded

**Comment by rtiangha** [comment]
I'm taking a stab at it, but since these are just volunteer hours, no promises.

I do have a question though:  How does the Discord RPC stuff work? Is it really needed now? I'm looking at the code, and am I right to assume that it was tied deeply to Citra Web Services? And that now that server is down, it makes the Discord stuff pretty much useless because you needed a Citra account to access it? Or is there a standalone way to access the Discord functionality? 

Sorry for the dumb questions; I don't use Discord in general and I can't (easily?) see a way to configure an account in the GUI (and I never had a Citra account before the shutdown so I don't how that functionality worked).

**Comment by rtiangha** [comment]
Well, just an update. I've got it working on my tree, but it keeps failing when I try to merge. It looks like my Vulkan stuff is slightly different than yours. So I guess I'll rebase and start over with just the Vulkan stuff, but that might mean I won't finish by end of today. We'll see.

**Comment by rtiangha** [comment]
OK, pull request sent to your branch. I think I've done all I can do though; felt like trying to do surgery with a butcher's knife. Someone please check my work (and fix it, if possible, lol).

**Comment by Miguel-hrvs** [comment]
I have the same questions as you about the discord-rpc stuff. I'm trying to solve the conflicts to merge. Thanks for the work :).

**Comment by Miguel-hrvs** [comment]
Conflicts solved, your progress is merged in my branch

**Comment by Miguel-hrvs** [comment]
I'm closing the issue now that it's solved. Thanks again for the help.
